### ISSUE TITLE
Error while testing bbduk

### ISSUE THREAD

**Issue by fgvieira** [snakemake/snakemake-wrappers#1129]
**Snakemake version**
`snakemake` version: `7.24.2`.
`snakemake-wrappers` version: `1.23.5`

**Describe the bug**
While working on a new PR (#1152), got this error when running tests for `bbtools`:

```
[Thu Mar 16 15:43:25 2023]
rule bbduk_pe:
    input: reads/pe/a.1.fastq, reads/pe/a.2.fastq, reads/adapt.fas
    output: trimmed/pe/a.1.fastq, trimmed/pe/a.2.fastq, trimmed/pe/a.single.fastq, trimmed/pe/a.discarded.fastq, trimmed/pe/a.stats.txt
    log: logs/bbduk/pe/a.log
    jobid: 0
    reason: Missing output files: trimmed/pe/a.stats.txt
    wildcards: sample=a
    threads: 2
    resources: tmpdir=/tmp

python -c "from __future__ import print_function; import sys, json; print(json.dumps([sys.version_info.major, sys.version_info.minor]))"
Activating conda environment: .snakemake/conda/4a24c5036b43522bf63eea289b22bf9d_
python ./snakemake-wrappers/bio/bbtools/bbduk/test/.snakemake/scripts/tmpx6a7akns.wrapper.py
Activating conda environment: .snakemake/conda/4a24c5036b43522bf63eea289b22bf9d_
Traceback (most recent call last):
  File "./snakemake-wrappers/bio/bbtools/bbduk/test/.snakemake/scripts/tmpx6a7akns.wrapper.py", line 3, in <module>
    import sys; sys.path.extend(['./micromamba/envs/snakemake_env/lib/python3.11/site-packages', './.cache/snakemake/snakemake/source-cache/runtime-cache/tmp_e9z1qxe/file/snakemake-wrappers/bio/bbtools/bbduk', './snakemake-wrappers/bio/bbtools/bbduk']); import pickle; snakemake = pickle.loads(b"\x80\x04\x95a\x06\x00\x00\x00\x00\x00\x00\x8c\x10snakemake.script\x94\x8c\tSnakemake\x94\x93\x94)\x81\x94}\x94(\x8c\x05input\x94\x8c\x0csnakemake.io\x94\x8c\nInputFiles\x94\x93\x94)\x81\x94(\x8c\x12reads/pe/a.1.fastq\x94\x8c\x12reads/pe/a.2.fastq\x94\x8c\x0freads/adapt.fas\x94e}\x94(\x8c\x06_names\x94}\x94(\x8c\x06sample\x94K\x00K\x02\x86\x94\x8c\x08adapters\x94K\x02N\x86\x94u\x8c\x12_allowed_overrides\x94]\x94(\x8c\x05index\x94\x8c\x04sort\x94eh\x16\x8c\tfunctools\x94\x8c\x07partial\x94\x93\x94h\x06\x8c\x19Namedlist._used_attribute\x94\x93\x94\x85\x94R\x94(h\x1c)}\x94\x8c\x05_name\x94h\x16sNt\x94bh\x17h\x1ah\x1c\x85\x94R\x94(h\x1c)}\x94h h\x17sNt\x94bh\x10h\x06\x8c\tNamedlist\x94\x93\x94)\x81\x94(h\nh\x0be}\x94(h\x0e}\x94h\x14]\x94(h\x16h\x17eh\x16h\x1ah\x1c\x85\x94R\x94(h\x1c)}\x94h h\x16sNt\x94bh\x17h\x1ah\x1c\x85\x94R\x94(h\x1c)}\x94h h\x17sNt\x94bubh\x12h\x0cub\x8c\x06output\x94h\x06\x8c\x0bOutputFiles\x94\x93\x94)\x81\x94(\x8c\x14trimmed/pe/a.1.fastq\x94\x8c\x14trimmed/pe/a.2.fastq\x94\x8c\x19trimmed/pe/a.single.fastq\x94\x8c\x1ctrimmed/pe/a.discarded.fastq\x94\x8c\x16trimmed/pe/a.stats.txt\x94e}\x94(h\x0e}\x94(\x8c\x07trimmed\x94K\x00K\x02\x86\x94\x8c\tsingleton\x94K\x02N\x86\x94\x8c\tdiscarded\x94K\x03N\x86\x94\x8c\x05stats\x94K\x04N\x86\x94uh\x14]\x94(h\x16h\x17eh\x16h\x1ah\x1c\x85\x94R\x94(h\x1c)}\x94h h\x16sNt\x94bh\x17h\x1ah\x1c\x85\x94R\x94(h\x1c)}\x94h h\x17sNt\x94bh?h')\x81\x94(h8h9e}\x94(h\x0e}\x94h\x14]\x94(h\x16h\x17eh\x16h\x1ah\x1c\x85\x94R\x94(h\x1c)}\x94h h\x16sNt\x94bh\x17h\x1ah\x1c\x85\x94R\x94(h\x1c)}\x94h h\x17sNt\x94bubhAh:hCh;hEh<ub\x8c\x06params\x94h\x06\x8c\x06Params\x94\x93\x94)\x81\x94\x8c\x98ref=reads/adapt.fas,adapters,artifacts ktrim=r k=23 mink=11 hdist=1 tpe tbo trimpolygright=10 minlen=25 maxns=30 entropy=0.5 entropywindow=50 entropyk=5\x94a}\x94(h\x0e}\x94\x8c\x05extra\x94K\x00N\x86\x94sh\x14]\x94(h\x16h\x17eh\x16h\x1ah\x1c\x85\x94R\x94(h\x1c)}\x94h h\x16sNt\x94bh\x17h\x1ah\x1c\x85\x94R\x94(h\x1c)}\x94h h\x17sNt\x94bhch`ub\x8c\twildcards\x94h\x06\x8c\tWildcards\x94\x93\x94)\x81\x94\x8c\x01a\x94a}\x94(h\x0e}\x94\x8c\x06sample\x94K\x00N\x86\x94sh\x14]\x94(h\x16h\x17eh\x16h\x1ah\x1c\x85\x94R\x94(h\x1c)}\x94h h\x16sNt\x94bh\x17h\x1ah\x1c\x85\x94R\x94(h\x1c)}\x94h h\x17sNt\x94bh\x10hrub\x8c\x07threads\x94K\x02\x8c\tresources\x94h\x06\x8c\tResources\x94\x93\x94)\x81\x94(K\x02K\x01\x8c\x04/tmp\x94e}\x94(h\x0e}\x94(\x8c\x06_cores\x94K\x00N\x86\x94\x8c\x06_nodes\x94K\x01N\x86\x94\x8c\x06tmpdir\x94K\x02N\x86\x94uh\x14]\x94(h\x16h\x17eh\x16h\x1ah\x1c\x85\x94R\x94(h\x1c)}\x94h h\x16sNt\x94bh\x17h\x1ah\x1c\x85\x94R\x94(h\x1c)}\x94h h\x17sNt\x94bh\x88K\x02h\x8aK\x01h\x8ch\x85ub\x8c\x03log\x94h\x06\x8c\x03Log\x94\x93\x94)\x81\x94\x8c\x13logs/bbduk/pe/a.log\x94a}\x94(h\x0e}\x94h\x14]\x94(h\x16h\x17eh\x16h\x1ah\x1c\x85\x94R\x94(h\x1c)}\x94h h\x16sNt\x94bh\x17h\x1ah\x1c\x85\x94R\x94(h\x1c)}\x94h h\x17sNt\x94bub\x8c\x06config\x94}\x94\x8c\x04rule\x94\x8c\x08bbduk_pe\x94\x8c\x0fbench_iteration\x94N\x8c\tscriptdir\x94\x8c6./snakemake-wrappers/bio/bbtools/bbduk\x94ub."); from snakemake.logging import logger; logger.printshellcmds = True; __real_file__ = __file__; __file__ = './snakemake-wrappers/bio/bbtools/bbduk/wrapper.py';
  File "./snakemake-wrappers/bio/bbtools/bbduk/test/.snakemake/conda/4a24c5036b43522bf63eea289b22bf9d_/lib/jvm/graalvm-189e927686-java17-22.3.0/languages/python/lib-python/3/pickle.py", line 1757, in _loads
    return _Unpickler(file, fix_imports=fix_imports, buffers=buffers,
  File "./snakemake-wrappers/bio/bbtools/bbduk/test/.snakemake/conda/4a24c5036b43522bf63eea289b22bf9d_/lib/jvm/graalvm-189e927686-java17-22.3.0/languages/python/lib-python/3/pickle.py", line 1210, in load
    dispatch[key[0]](self)
  File "./snakemake-wrappers/bio/bbtools/bbduk/test/.snakemake/conda/4a24c5036b43522bf63eea289b22bf9d_/lib/jvm/graalvm-189e927686-java17-22.3.0/languages/python/lib-python/3/pickle.py", line 1535, in load_stack_global
    self.append(self.find_class(module, name))
  File "./snakemake-wrappers/bio/bbtools/bbduk/test/.snakemake/conda/4a24c5036b43522bf63eea289b22bf9d_/lib/jvm/graalvm-189e927686-java17-22.3.0/languages/python/lib-python/3/pickle.py", line 1577, in find_class
    __import__(module, level=0)
  File "./micromamba/envs/snakemake_env/lib/python3.11/site-packages/snakemake/__init__.py", line 24, in <module>
    from snakemake.workflow import Workflow
  File "./micromamba/envs/snakemake_env/lib/python3.11/site-packages/snakemake/workflow.py", line 25, in <module>
    from snakemake.rules import Rule, Ruleorder, RuleProxy
  File "./micromamba/envs/snakemake_env/lib/python3.11/site-packages/snakemake/rules.py", line 1350, in <module>
    class RuleProxy:
  File "./micromamba/envs/snakemake_env/lib/python3.11/site-packages/snakemake/rules.py", line 1355, in RuleProxy
    def output(self):
  File "./micromamba/envs/snakemake_env/lib/python3.11/site-packages/snakemake/common/__init__.py", line 213, in __init__
    super().__init__(method, doc=method.__doc__)
AttributeError: 'lazy_property' object has no attribute '__doc__'
```

**Minimal example**
Run the test for `bbtools/bbduk` wrapper.

**Comment by fgvieira** [comment]
It seems it was because of an old python version being deployed by the recipe. Closing.
