### ISSUE TITLE
FastQC resource allocation not working as expected - get_mem fix?

### ISSUE THREAD

**Issue by supermaxiste** [snakemake/snakemake-wrappers#1840]
**Snakemake version**
Snakemake version from snakemake-github-action@v1.25.1 (latest) and FastQC wrapper v2.6.0 (latest).

**Describe the bug**
The wrapper is not able to access memory resources provided. This happens both when specifying `--resources mem_mb=4096` when running snakemake and specifying resources in the `resources:` argument of the wrapper. When using >3 cores, this leads to the error:
```
Memory value 68 MB was outside the allowed range (100 - 10000) at /github/workspace/.test/.snakemake/conda/0346c7f3b820da8a41d207405da5d87d_/bin/fastqc line 203.
```
This results because the line `mem_mb = int(get_mem(snakemake, "MiB") / snakemake.threads)` form the FastQC wrapper calling `get_mem` seems to result in 205Mb. When checking `get_mem` code:
```
    # Store memory in MiB


    if mem_mb := snakemake.resources.get("mem_gb", None):
        mem_mb *= 1024
    else:
        mem_mb = snakemake.resources.get("mem_mb", 205)
```
https://github.com/snakemake/snakemake-wrapper-utils/blob/f329b2b64ffbf1a4e4369c470f82b0690c9c43fd/snakemake_wrapper_utils/snakemake.py#L7-L12

The `if` condition uses only "mem_gb", leading to default `mem_mb=205`.
I'm wondering if there could be an `elif` getting "mem_mb"? If not, the wrapper usage should be changed to use `mem_gb` instead of `mem_mb`.

**Logs**
```
rule fastqc:
    input: data/test_pe_R2.fastq.gz
    output: results/fastqc/test_pe_R2.html, results/fastqc/test_pe_R2_fastqc.zip
    log: logs/fastqc/test_pe_R2.log
    jobid: 3
    reason: Missing output files: results/fastqc/test_pe_R2_fastqc.zip
    wildcards: sample=test_pe, extension=R2
    threads: 3
    resources: tmpdir=/tmp, mem_mb=4096, mem_mib=3907

Activating conda environment: .snakemake/conda/f2a6a25dedb87c56ea757159e1ca9126_
Activating conda environment: .snakemake/conda/f2a6a25dedb87c56ea757159e1ca9126_
Traceback (most recent call last):
  File "/github/workspace/.test/.snakemake/scripts/tmpspw7fxy4.wrapper.py", line 49, in <module>
    shell(
  File "/opt/conda/envs/snakemake/lib/python3.11/site-packages/snakemake/shell.py", line 294, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  fastqc --threads 3 --memory 68 --quiet --outdir /tmp/tmprmbijdoi data/test_pe_R2.fastq.gz  > logs/fastqc/test_pe_R2.log 2>&1' returned non-zero exit status 2.
[Fri Sep 29 07:43:24 2023]
Error in rule fastqc:
    jobid: 3
    input: data/test_pe_R2.fastq.gz
    output: results/fastqc/test_pe_R2.html, results/fastqc/test_pe_R2_fastqc.zip
    log: logs/fastqc/test_pe_R2.log (check log file(s) for error details)
    conda-env: /github/workspace/.test/.snakemake/conda/f2a6a25dedb87c56ea757159e1ca9126_
Logfile logs/fastqc/test_pe_R2.log:
================================================================================
Memory value 68 MB was outside the allowed range (100 - 10000) at /github/workspace/.test/.snakemake/conda/f2a6a25dedb87c56ea757159e1ca9126_/bin/fastqc line 203.
================================================================================
```

**Minimal example**
Using the FastQC wrapper with `threads: 3` or more.

**Additional context**
None

**Comment by supermaxiste** [comment]
I tested the issue out and changing the wrappers `resource` to `mem_gb` fixes the issue. I will make a PR request soon.

**Comment by fgvieira** [comment]
Can you send the `snakemake` code you are using to reproduce the error?
