### ISSUE TITLE
FastQC wrapper doesn't support *.fq.gz reads after #14 fix

### ISSUE THREAD

**Issue by iromeo** [snakemake/snakemake-wrappers#214]
**Snakemake version**
Snakemake wrappers version 0.64.0,
Snakemake version any (e.g. 5.26.1)

**Describe the bug**

FASTA or FASTQ files could be often be named like `*.fq.gz`.  Starting from 0.50.0 version fastqc wrapper doesn't support such naming conventions and always fails for such files. It happens because now FASTQC tools and wrapper expect different name for result file and as a result, the wrapper cannot find the report file.

E.g. for `foo_1.fq.gz` FASTQC generates `foo_1_fastqc.html` report. Wrappers < 0.50.0 also uses the same naming conventions, but after #14 fix the wrapper expects `foo_1.fq_fastqc.html` which doesn't exist, so `mv` command fails with file not found error.

**Logs**
```
fastqc  --quiet -t 1 --outdir /scratch1/fs1/martyomov/rcherniatchik/pilot_small/tmp/tmp7kg3b6vx bams/A01/V300010918_L4_HUMvotMAAAAAAA-1_hg38_unmapped_reads_1.fq.gz  2> qc/bams_unmapped/A01/V300010918_L4_HUMvotMAAAAAAA-1_hg38_unmapped_reads_1_fastqc.log
mv /scratch1/fs1/martyomov/rcherniatchik/pilot_small/tmp/tmp7kg3b6vx/V300010918_L4_HUMvotMAAAAAAA-1_hg38_unmapped_reads_1.fq_fastqc.html qc/bams_unmapped/A01/V300010918_L4_HUMvotMAAAAAAA-1_hg38_unmapped_reads_1_fastqc.html
mv: cannot stat '/scratch1/fs1/martyomov/rcherniatchik/pilot_small/tmp/tmp7kg3b6vx/V300010918_L4_HUMvotMAAAAAAA-1_hg38_unmapped_reads_1.fq_fastqc.html': No such file or directory
Traceback (most recent call last):
  File "/scratch1/fs1/martyomov/rcherniatchik/pilot_small/.snakemake/scripts/tmpgp95haer.wrapper.py", line 47, in <module>
    shell("mv {html_path} {snakemake.output.html}")
  File "/opt/conda/lib/python3.7/site-packages/snakemake/shell.py", line 176, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  mv /scratch1/fs1/martyomov/rcherniatchik/pilot_small/tmp/tmp7kg3b6vx/V300010918_L4_HUMvotMAAAAAAA-1_hg38_unmapped_reads_1.fq_fastqc.html qc/bams_unmapped/A01/V300010918_L4_HUMvotMAAAAAAA-1_hg38_unmapped_reads_1_fastqc.html' returned non-zero exit status 1.
```

Work dir folder content:
```shell
$ ls /scratch1/fs1/martyomov/rcherniatchik/pilot_small/tmp/tmp7kg3b6vx/

V300010918_L4_HUMvotMAAAAAAA-1_hg38_unmapped_reads_1_fastqc.html 
V300010918_L4_HUMvotMAAAAAAA-1_hg38_unmapped_reads_1_fastqc.zip
```

**Minimal example**
```
rule fastqc:
    input:
        "reads/{sample}.fq.gz"
    output:
        html="qc/fastqc/{sample}.html",
        zip="qc/fastqc/{sample}_fastqc.zip"
    log:
        "logs/fastqc/{sample}.log"
    threads: 1
    wrapper:
        "master/bio/fastqc"
```

**Additional context**
Before #14 `basename_without_ext` method was:
```python
   split_ind = 2 if base.endswith(".gz") else 1
    base = ".".join(base.split(".")[:-split_ind])
```

after:
```python
    split_ind = 2 if base.endswith(".fastq.gz") else 1
    base = ".".join(base.split(".")[:-split_ind])
```

**Comment by lparsons** [comment]
It looks like these lines might be what FastQC is using to construct the output filename:

https://github.com/s-andrews/FastQC/blob/55c27c5123d53f1c294be10fdae3fad8b390cce0/uk/ac/babraham/FastQC/Analysis/OfflineRunner.java#L180-L185
```java
		if (FastQCConfig.getInstance().output_dir != null) {
			String fileName = file.getFile().getName().replaceAll("stdin:","").replaceAll("\\.gz$","").replaceAll("\\.bz2$","").replaceAll("\\.txt$","").replaceAll("\\.fastq$", "").replaceAll("\\.fq$", "").replaceAll("\\.csfastq$", "").replaceAll("\\.sam$", "").replaceAll("\\.bam$", "")+"_fastqc.html";
			reportFile = new File(FastQCConfig.getInstance().output_dir+"/"+fileName);						
		}
		else {
			reportFile = new File(file.getFile().getAbsolutePath().replaceAll("stdin:","").replaceAll("\\.gz$","").replaceAll("\\.bz2$","").replaceAll("\\.txt$","").replaceAll("\\.fastq$", "").replaceAll("\\.fq$", "").replaceAll("\\.csfastq$", "").replaceAll("\\.sam$", "").replaceAll("\\.bam$", "")+"_fastqc.html");			
```
The wrapper will need to replicate that logic.

**Comment by lczech** [comment]
This seems to be solved in [issue 288](https://github.com/snakemake/snakemake-wrappers/issues/288) and [PR 300](https://github.com/snakemake/snakemake-wrappers/pull/300).
