### ISSUE TITLE
Conda fails to build remote env for custom wrapper. Works locally. 

### ISSUE THREAD

**Issue by Linkrw12** [snakemake/snakemake-wrappers#237]
I've made a custom wrapper in a [local repo](https://github.com/DamLabResources/pipeline-multitool/tree/main/nni_automation). When I use the wrapper locally, the environment is built just fine and everything runs as expected. However, when I try to call it through github, conda will fail to build ```environment.yaml```. For reference, I've been able to run wrappers for this [test case](https://github.com/snakemake/snakemake-wrappers/tree/master/bio/arriba/test) and this [test case](https://github.com/snakemake/snakemake-wrappers/tree/master/bio/hmmer/hmmbuild/test) for other wrappers without any issues. 

I've tried modifying the environment file several different ways:
* removing anything cuda related
* removing the rapidsai channel and packages
* removing the python version specification
* removing the python dependency
* removing all pip packages
* modifying yaml tab spacing
* removing the name argument
* combinations of the above

I've even tried using an absolute path for the wrapper as opposed to specifying a prefix. But nothing seems to be working. Here's an [example](https://github.com/DamLabResources/pipeline-multitool/tree/main/nni_automation/example) that replicates the error. 

snakemake version: 5.26.1

Here's the Snakefile:
```
configfile: "config.yaml"

MODELS = config["NNI_MODEL_PARAMS"].keys()

rule optimize_hypperparameters:
    output:
        experiment   = expand("nni/{model}_experiments.yaml", 
                               model = MODELS),
                                
        search_space = expand("nni/search_space/{model}_search_space.json",
                               model = MODELS),
                               
        experiment_results = expand("nni/experiment_results/{model}.csv", 
                                    model = MODELS)
    wrapper:
        "https://github.com/DamLabResources/pipeline-multitool/tree/main/nni_automation"
```

Here's the output log:
```
Building DAG of jobs...
Creating conda environment https:/github.com/DamLabResources/pipeline-multitool/tree/main/nni_automation/environment.yaml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /tmp/tmpc5g0j_1m.yaml:

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/robertlink/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/robertlink/anaconda3/lib/python3.7/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/robertlink/anaconda3/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 86, in execute
        spec = specs.detect(name=name, filename=filename, directory=os.getcwd())
      File "/home/robertlink/anaconda3/lib/python3.7/site-packages/conda_env/specs/__init__.py", line 43, in detect
        if spec.can_handle():
      File "/home/robertlink/anaconda3/lib/python3.7/site-packages/conda_env/specs/yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "/home/robertlink/anaconda3/lib/python3.7/site-packages/conda_env/env.py", line 157, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/home/robertlink/anaconda3/lib/python3.7/site-packages/conda_env/env.py", line 138, in from_yaml
        data = yaml_safe_load(yamlstr)
      File "/home/robertlink/anaconda3/lib/python3.7/site-packages/conda/common/serialize.py", line 67, in yaml_safe_load
        return yaml.safe_load(string, version="1.2")
      File "/home/robertlink/anaconda3/lib/python3.7/site-packages/ruamel_yaml/main.py", line 980, in safe_load
        return load(stream, SafeLoader, version)
      File "/home/robertlink/anaconda3/lib/python3.7/site-packages/ruamel_yaml/main.py", line 935, in load
        return loader._constructor.get_single_data()
      File "/home/robertlink/anaconda3/lib/python3.7/site-packages/ruamel_yaml/constructor.py", line 109, in get_single_data
        node = self.composer.get_single_node()
      File "/home/robertlink/anaconda3/lib/python3.7/site-packages/ruamel_yaml/composer.py", line 78, in get_single_node
        document = self.compose_document()
      File "/home/robertlink/anaconda3/lib/python3.7/site-packages/ruamel_yaml/composer.py", line 104, in compose_document
        self.parser.get_event()
      File "/home/robertlink/anaconda3/lib/python3.7/site-packages/ruamel_yaml/parser.py", line 163, in get_event
        self.current_event = self.state()
      File "/home/robertlink/anaconda3/lib/python3.7/site-packages/ruamel_yaml/parser.py", line 239, in parse_document_end
        token = self.scanner.peek_token()
      File "/home/robertlink/anaconda3/lib/python3.7/site-packages/ruamel_yaml/scanner.py", line 182, in peek_token
        self.fetch_more_tokens()
      File "/home/robertlink/anaconda3/lib/python3.7/site-packages/ruamel_yaml/scanner.py", line 282, in fetch_more_tokens
        return self.fetch_value()
      File "/home/robertlink/anaconda3/lib/python3.7/site-packages/ruamel_yaml/scanner.py", line 655, in fetch_value
        self.reader.get_mark(),
    ruamel_yaml.scanner.ScannerError: mapping values are not allowed here
      in "<unicode string>", line 148, column 34:
            <span style="background-color: #79b8ff;width: 0%;" class="Pro ... 
                                         ^ (line: 148)

`$ /home/robertlink/anaconda3/bin/conda-env create --quiet --file /home/robertlink/nni_wrapper_test/.snakemake/conda/2002495d.yaml --prefix /home/robertlink/nni_wrapper_test/.snakemake/conda/2002495d`

  environment variables:
                 CIO_TEST=<not set>
                 CNI_PATH=/home/robertlink/anaconda3/lib/cni
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/robertlink/anaconda3/bin/conda
CONDA_MKL_INTERFACE_LAYER_BACKUP=
             CONDA_PREFIX=/home/robertlink/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/robertlink/anaconda3/bin/python
               CONDA_ROOT=/home/robertlink/anaconda3
              CONDA_SHLVL=1
                CUDA_PATH=/home/robertlink/anaconda3
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64:/usr/local/cuda/extras/CUPTI/lib64
                     PATH=/usr/local/cuda-10.2/bin:/home/robertlink/edirect:/home/robertlink/CNN
                          _promoter_prediction/Jurkat_CNN_transcriptome/Jurkat_RNA_Seq_Processin
                          g/Dart:/home/robertlink/sratoolkit.2.8.2-1-ubuntu64/bin:/home/robertli
                          nk/cd-hit-v4.8.1-2019-0228:/usr/local/cuda-10.0/bin:/home/robertlink/b
                          in:/home/robertlink/.local/bin:/usr/local/cuda-10.2/bin:/home/robertli
                          nk/anaconda3/bin:/home/robertlink/anaconda3/condabin:/home/robertlink/
                          edirect:/home/robertlink/CNN_promoter_prediction/Jurkat_CNN_transcript
                          ome/Jurkat_RNA_Seq_Processing/Dart:/home/robertlink/sratoolkit.2.8.2-1
                          -ubuntu64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:
                          /bin:/usr/games:/usr/local/games:/snap/bin
               PYTHONPATH=/home/robertlink/custom_python_modules:/home/robertlink/custom_python_
                          modules:
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /home/robertlink/anaconda3
            shell level : 1
       user config file : /home/robertlink/.condarc
 populated config files : 
          conda version : 4.8.5
    conda-build version : 3.18.11
         python version : 3.7.8.final.0
       virtual packages : __cuda=10.2
                          __glibc=2.27
       base environment : /home/robertlink/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/robertlink/anaconda3/pkgs
                          /home/robertlink/.conda/pkgs
       envs directories : /home/robertlink/anaconda3/envs
                          /home/robertlink/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.5 requests/2.24.0 CPython/3.7.8 Linux/5.4.0-47-generic ubuntu/18.04.4 glibc/2.27
                UID:GID : 1002:1002
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.


  File "/home/robertlink/anaconda3/lib/python3.7/site-packages/snakemake/deployment/conda.py", line 352, in create
```

Any thoughts or help would be very appreciated. Thanks!

**Comment by dlaehnemann** [comment]
From the backtrace it sounds like something goes wrong in parsing the `yaml` format of the `environment.yaml`. But I have no clue where that HTML / CSS code is coming from. A wild guess (simply because I have never seen this before): the `  -pip:` substructure doesn't work as expected?
But weird that it works locally and not with GitHub Actions. Maybe different version of `ruamel_yaml` that are being used? Or different versions of `conda`? Maybe try using `--conda-frontend mamba` to see if mamba does not have that bug?

**Comment by dlaehnemann** [comment]
@johanneskoester suggested:
> Try to add --conda-cleanup-pkgs tarballs cache to the snakemake invocation in the test function. This way, we should remove all unneeded conda data after each test.
In addition, maybe even actively delete the environments from the test directory. They are not needed for subsequent tests

**Comment by Linkrw12** [comment]
The same error gets thrown when I use ```--conda-frontend mamba```. And yeah, it seems to throw that error when it's unable to parse the yaml file. I've tried to play around with the yaml file spacing today, but to no avail. Everything still runs fine using the env file locally, but not when called with GitHub

Apologizes, but how would I check what version ruamel_yaml and conda GitHub Actions are using? I've been having trouble finding out how Snakemake executes github wrappers on the backend. Here are my tools' versions:

Conda:
```bash
$ conda info
     active environment : base
    active env location : /home/robertlink/anaconda3
            shell level : 1
       user config file : /home/robertlink/.condarc
 populated config files : 
          conda version : 4.9.1
    conda-build version : 3.20.5
         python version : 3.7.8.final.0
       virtual packages : __cuda=10.2=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/robertlink/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/robertlink/anaconda3/pkgs
                          /home/robertlink/.conda/pkgs
       envs directories : /home/robertlink/anaconda3/envs
                          /home/robertlink/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.1 requests/2.24.0 CPython/3.7.8 Linux/5.4.0-52-generic ubuntu/18.04.4 glibc/2.27
                UID:GID : 1002:1002
             netrc file : None
           offline mode : False
```

ruamel_yaml versions
```bash
$ pip freeze | grep yaml
ruamel-yaml==0.15.87
ruamel.yaml.clib==0.2.2
```

And here's the env file:
```yaml
name: nni_training_env
channels:
  - conda-forge
  - rapidsai
  - anaconda
dependencies:
  - cudatoolkit=10.2
  - python=3.7
  - rapids
  - pip
  - pip:
    - snakemake
    - deepmerge
    - nni
    - matplotlib
    - scikit-learn 
    - pandas
    - scipy
    - xgboost
    - torch
    - fastai==1.0.61
    - tensorflow
    - theano
    - keras
```

Is there anything that seems fishy with any of these files/outputs?

**Comment by nikostr** [comment]
Hey, was this ever resolved? I'm coming up against the same issue. Testing the wrapper locally using the `test.py` works fine, but when I try with the URL I come up against the same error.

**Comment by Linkrw12** [comment]
That's what I ended up doing as well, but incredibly inconvenient for all of our other rigs in the lab to do the same...

**Comment by nikostr** [comment]
Hey, I did some digging, and fount this:

https://github.com/snakemake/snakemake/blob/81922b6200cbf5b62bf27737e12e0905ce8c540f/snakemake/wrapper.py#L17

So, changing from `tree` to `raw` in the URL seems to solve this for me.

**Comment by dlaehnemann** [comment]
Great find, @nikostr! Just to be sure, this would e.g. mean changing `tree` to `raw` in [this exact line of @Linkrw12's original example](https://github.com/DamLabResources/pipeline-multitool/blob/b71586e36189ef72418ad91461e772875f400260/nni_automation/example/Snakefile#L16), right?

If this solves it for you, @Linkrw12 , feel free to close this issue.

**Comment by nikostr** [comment]
Yes, that seems to solve it for me @dlaehnemann :) It would probably make sense to be more explicit about this in the snakemake(-wrappers) documentation.

**Comment by dlaehnemann** [comment]
Excellent point, I've created a PR #335 with an concrete example for the docs. Feel free to comment on the wording or suggest further changes!
