### ISSUE TITLE
salmon_quant wrapper shell script bug

### ISSUE THREAD

**Issue by radio1988** [snakemake/snakemake-wrappers#2939]
**Snakemake version**
8.11.3

**Describe the bug**
```
/usr/bin/bash: -c: line 1: syntax error near unexpected token `(' 
```
is triggered when running this  wrapper ("v3.10.2/bio/salmon/quant")

This happens on all the different dataset I have. This did not happen before yesterday. I was able to use this wrapper before yesterday.

**Logs**
My submission code:
```
snakemake -p  --use-conda --conda-prefix ~/anaconda3/envs/osr_envs --latency-wait 120 --ri --restart-times 0 --rerun-triggers mtime --cores=16  -j 1 -k
```

```
localrule salmon_quant_pe:
    input: trimmed/B3.R1.fastq.gz, trimmed/B3.R2.fastq.gz, /home/rui/genomes/mm10_ensembl/Mus_musculus.GRCm39.112.gtf.gentrome.fa.salmon_idx/complete_ref_lens.bin
    output: salmon/B3/quant.sf, salmon/B3/lib_format_counts.json
    log: salmon/B3/log.txt
    jobid: 216
    benchmark: salmon/B3/benchmark.txt
    reason: Missing output files: salmon/B3/quant.sf
    wildcards: sample=B3
    threads: 4
    resources: tmpdir=/tmp, mem_mb=6000, mem_mib=5723

Activating conda environment: ../anaconda3/envs/osr_envs/125c14cb9ade0187c9b5056aaaa49dc8_
/usr/bin/bash: -c: line 1: syntax error near unexpected token `('
/usr/bin/bash: -c: line 1: `set -euo pipefail;  salmon quant --index functools.partial(<function Namedlist._used_attribute at 0x7fc2dc94c680>, _name='index')  --libType A  --mates1 trimmed/B3.R1.fastq.gz  --mates2 trimmed/B3.R2.fastq.gz --output salmon/B3   --threads 4    > salmon/B3/log.txt 2>&1'
Traceback (most recent call last):
  File "/home/rui/2401_ana_RNASeq/.snakemake/scripts/tmp9ockufka.wrapper.py", line 114, in <module>
    shell(
  File "/home/rui/anaconda3/envs/s8/lib/python3.12/site-packages/snakemake/shell.py", line 297, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  salmon quant --index functools.partial(<function Namedlist._used_attribute at 0x7fc2dc94c680>, _name='index')  --libType A  --mates1 trimmed/B3.R1.fastq.gz  --mates2 trimmed/B3.R2.fastq.gz --output salmon/B3   --threads 4    > salmon/B3/log.txt 2>&1' returned non-zero exit status 2.
```

**Minimal example**
My Code:
```
if config["PAIR_END"]:
    rule salmon_quant_pe:
        input:
            r1="trimmed/{sample}.R1.fastq.gz",
            r2="trimmed/{sample}.R2.fastq.gz",
            index=GENTROME + ".salmon_idx",
            flag=GENTROME + ".salmon_idx/complete_ref_lens.bin"
        output:
            quant="salmon/{sample}/quant.sf",
            lib="salmon/{sample}/lib_format_counts.json"
        log:
            "salmon/{sample}/log.txt",
        benchmark:
            "salmon/{sample}/benchmark.txt",
        params:
            # optional parameters
            libtype="A",
            extra="",
        threads:
            4
        resources:
            mem_mb=lambda wildcards, attempt: attempt * 6000  # 18G for human
        wrapper:
            "v3.10.2/bio/salmon/quant"
```

**Additional context**
This did not happen a week ago, it happened since yesterday

Thanks for the help!

Rui

**Comment by fgvieira** [comment]
What is `GENTROME`?

**Comment by radio1988** [comment]
It's a fasta file concatenating transcripts and genome. A docoy file tells salmon which sequences are genome. And help with the counting
________________________________

**Comment by fgvieira** [comment]
I'd say there is something wrong with your index, since `snakemake` resolves it to:
```
[...] --index functools.partial(<function Namedlist._used_attribute at 0x7fc2dc94c680>, _name='index')  --libType A [...]
```

Furthermore, the `index` does not appear as a rule input:
```
[...]
 input: trimmed/B3.R1.fastq.gz, trimmed/B3.R2.fastq.gz, /home/rui/genomes/mm10_ensembl/Mus_musculus.GRCm39.112.gtf.gentrome.fa.salmon_idx/complete_ref_lens.bin
[...]
```

**Comment by radio1988** [comment]
Hmm... I'm not sure. I've switched to using snakemake 'conda' method for the environment, and it worked. I did not change the index. But if you can't reproduce the problem. I guess it's hard for you to debug. It's okay.

**Comment by radio1988** [comment]
Yes, the index is not a rule input. The previous rule look like this, and I just used one of the filenames as input:
```
rule salmon_index:
    input:
        sequences=GENTROME,
        decoys=DECOYS
    output:
        index=directory(GENTROME + ".salmon_idx/"),
        others=multiext(
            GENTROME + ".salmon_idx/",
            "complete_ref_lens.bin",
            "ctable.bin",
            "ctg_offsets.bin",
            "duplicate_clusters.tsv",
            "info.json",
            "mphf.bin",
            "pos.bin",
            "pre_indexing.log",
            "rank.bin",
            "refAccumLengths.bin",
            "ref_indexing.log",
            "reflengths.bin",
            "refseq.bin",
            "seq.bin",
            "versionInfo.json"
        ),
    log:
        GENTROME + ".salmon_idx/log",
    benchmark:
        GENTROME + ".salmon_idx/benchmark",
    # hg38-ensembl s       h:m:s   max_rss max_vms max_uss max_pss io_in   io_out  mean_load       cpu_time
    # 1378.6924       0:22:58 19463.66        42060.36        19451.28        19452.22        9.68    18896.98        446.52  6156.25
    threads: 6
    resources:
        mem_mb=lambda wildcards, attempt: attempt * 4000
    params:
        extra=""
    wrapper:
        "v3.10.2/bio/salmon/index"
```

**Comment by radio1988** [comment]
I used the following as input:
            index=GENTROME + ".salmon_idx",

Yes, I got it working by not using the wrapper but using a custom conda.yaml file and a 'shell' rule

**Comment by radio1988** [comment]
The main issue seem like this line

```
/usr/bin/bash: -c: line 1: syntax error near unexpected token `('
```

Maybe it's a bash version issue

**Comment by fgvieira** [comment]
I think that comes from the parenthesis in `[...] --index functools.partial(<function Namedlist._used_attribute at 0x7fc2dc94c680>, _name='index') [...]`.
Somehow, `snakemake` did not call that function and just included its reference.

**Comment by fgvieira** [comment]
The strange thing is that the wrapper test (using the wrapper and conda) runs fine.

**Comment by radio1988** [comment]
I see. Thank you for looking into this! Since this issue can't be reproduced. I think we can close this issue.
