### ISSUE TITLE
ModuleNotFoundError: No module named 'snakemake_wrapper_utils'

### ISSUE THREAD

**Issue by megancamilla** [snakemake/snakemake-wrappers#391]
ModuleNotFoundError: No module named 'snakemake_wrapper_utils'

**Snakemake version**
Snakemake version 6.6 **and** snakemake-wrappers version 0.77.0 

**Describe the bug**
I am having issues running gatk wrappers using java MarkDuplicatesSpark and HaplotypeCaller with Snakemake. 

I am getting an early error: ModuleNotFoundError: No module named 'snakemake_wrapper_utils'
I have seen that this was an issue with an earlier version of Snakemake, which was fixed but maybe it still persists in these GATK wrappers somewhere? 

If I run:
`conda activate .snakemake/conda/15877a7da853a7ec57081487aa23fc62`
`gatk MarkDuplicatesSpark --input mapped/UV-2_S2.sorted.bam --output dedup/UV-2_S2.sorted.bam`

This completes without errors, so as far as I can tell it is not an issue with my input or output files.

**Logs**
`Activating conda environment: /Users/mcdonamc/GIT/GATK4_Zymoseptoria/.snakemake/conda/15877a7da853a7ec57081487aa23fc62
Traceback (most recent call last):
  File "/Users/mcdonamc/GIT/GATK4_Zymoseptoria/.snakemake/scripts/tmpchb5tezv.wrapper.py", line 14, in <module>
    from snakemake_wrapper_utils.java import get_java_opts
ModuleNotFoundError: No module named 'snakemake_wrapper_utils'
Traceback (most recent call last):
  File "/Users/mcdonamc/GIT/GATK4_Zymoseptoria/.snakemake/scripts/tmptfs5fit3.wrapper.py", line 14, in <module>
    from snakemake_wrapper_utils.java import get_java_opts
ModuleNotFoundError: No module named 'snakemake_wrapper_utils'
[Wed Jul 21 13:06:47 2021]
[Wed Jul 21 13:06:47 2021]
Error in rule haplotype_caller:
Error in rule haplotype_caller:
    jobid: 6
    jobid: 1
    output: calls/UV-2_S2.g.vcf
    output: calls/UV-1_S1.g.vcf
    log: logs/gatk/haplotypecaller/UV-2_S2.log (check log file(s) for error message)
    log: logs/gatk/haplotypecaller/UV-1_S1.log (check log file(s) for error message)
    conda-env: /Users/mcdonamc/GIT/GATK4_Zymoseptoria/.snakemake/conda/15877a7da853a7ec57081487aa23fc62
    conda-env: /Users/mcdonamc/GIT/GATK4_Zymoseptoria/.snakemake/conda/15877a7da853a7ec57081487aa23fc62
`
**Minimal example**
Add a minimal example for reproducing the bug.

**Additional context**

**Comment by megancamilla** [comment]
Apologies,

Very easy fix by doing 
`conda install snakemake-wrapper-utils` in my snakemake environment
