### ISSUE TITLE
VariantRecalibrator wrapper.py overwrite rule resouces

### ISSUE THREAD

**Issue by gbinux** [snakemake/snakemake-wrappers#395]
I got an error when using VariantRecalibrator wrapper:
```
Traceback (most recent call last):
  File "/Users/bing.guo/snp_call/.snakemake/scripts/tmp39q2_24h.wrapper.py", line 51, in <module>
    shell(
  File "/Users/bing.guo/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/shell.py", line 191, in __new__
    tmpdir_resource = resources.get("tmpdir", None)
AttributeError: 'list' object has no attribute 'get'
```
looks like the wrapper uses a list variable named `resources` which overwrites `snakemake/lib/python3.9/site-packages/snakemake/shell.py` `resources` variable which is from the rule's `resources` sepecifications.
https://github.com/snakemake/snakemake-wrappers/blob/f3a65298789c8c7b837b13544e65a79f649bda43/bio/gatk/variantrecalibrator/wrapper.py#L37

in shell.py:
```
resources = context.get("resources", {})
```

**Comment by gbinux** [comment]
BTW, there are two minor typos: rule name and wrapper string within the [example snakefile]
(https://snakemake-wrappers.readthedocs.io/en/stable/wrappers/gatk/variantrecalibrator.html?highlight=variantrecalibrator)

Other than this, the wrapper is great and makes life much easier!
