### ISSUE TITLE
BUG: Subread-FeatureCounts Wrapper fails to create Conda-Environment

### ISSUE THREAD

**Issue by KuechlerO** [snakemake/snakemake-wrappers#938]
**Snakemake version**
7.18.2

**Wrapper version**
`v1.19.2/bio/subread/featurecounts`

**Describe the bug**
Using the **Subread - Feature Counts** Snakemake wrapper failed, due to Conda environment error during set-up.

**Logs**
```
Building DAG of jobs...
Creating conda environment https://github.com/snakemake/snakemake-wrappers/raw/v1.19.2/bio/subread/featurecounts/environment.yaml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /var/folders/2h/x3d2xrpd66908__bf_8j7sqc0000gn/T/tmp2q6s554r.yaml:
Command:
mamba env create --quiet --file "/Users/oliverkuchler/Studium/Master_BioInfo_Berlin/Masterthesis/Topic_Splicing_Variants/splice-prediction/snakemake_workflows/Snakemake_Main/.snakemake/conda/334161c9f303f552bc10f078bbd9f540_.yaml" --prefix "/Users/oliverkuchler/Studium/Master_BioInfo_Berlin/Masterthesis/Topic_Splicing_Variants/splice-prediction/snakemake_workflows/Snakemake_Main/.snakemake/conda/334161c9f303f552bc10f078bbd9f540_"
Output:
Traceback (most recent call last):
  File "/Users/oliverkuchler/opt/miniconda3/condabin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/Users/oliverkuchler/opt/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 53, in <module>
    import mamba.mamba_api as api
ImportError: dlopen(/Users/oliverkuchler/opt/miniconda3/lib/python3.9/site-packages/mamba/mamba_api.cpython-39-darwin.so, 2): Library not loaded: @rpath/libarchive.13.dylib
  Referenced from: /Users/oliverkuchler/opt/miniconda3/lib/python3.9/site-packages/mamba/mamba_api.cpython-39-darwin.so
  Reason: image not found
```

**Minimal example**
Simple usage of wrapper...

**Additional context**
My OS: MacOs

**Comment by fgvieira** [comment]
That wrapper was last updated and tested a month ago, and all tests passed.
It could be something specific to Mac; have you tried running this wrapper's test locally?

**Comment by KuechlerO** [comment]
I just gave it a try, but the error is the same.

Here's the shell output:
```
(test-snakemake-wrappers) Olivers-MacBook-Pro-5:snakemake-wrappers oliverkuchler$ pytest test.py -k "subread"
==================================================================== test session starts ====================================================================
platform darwin -- Python 3.11.0, pytest-7.2.0, pluggy-1.0.0
rootdir: /Users/oliverkuchler/Zeugs_WebDev/Programming/GitProjekte/snakemake-wrappers
collected 429 items / 428 deselected / 1 selected                                                                                                           

test.py F                                                                                                                                             [100%]

========================================================================= FAILURES ==========================================================================
________________________________________________________________ test_subread_featurecounts _________________________________________________________________

    @skip_if_not_modified
    def test_subread_featurecounts():
>       run(
            "bio/subread/featurecounts",
            [
                "snakemake",
                "--cores",
                "1",
                "results/a.featureCounts",
                "results/a.featureCounts.summary",
                "results/a.featureCounts.jcounts",
                "--use-conda",
                "-F",
            ],
        )

test.py:3253: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test.py:130: in run
    raise e
test.py:111: in run
    subprocess.check_call(cmd)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

popenargs = (['snakemake', '--cores', '1', 'results/a.featureCounts', 'results/a.featureCounts.summary', 'results/a.featureCounts.jcounts', ...],)
kwargs = {}, retcode = 1
cmd = ['snakemake', '--cores', '1', 'results/a.featureCounts', 'results/a.featureCounts.summary', 'results/a.featureCounts.jcounts', ...]

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.
    
        The arguments are the same as for the call function.  Example:
    
        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           subprocess.CalledProcessError: Command '['snakemake', '--cores', '1', 'results/a.featureCounts', 'results/a.featureCounts.summary', 'results/a.featureCounts.jcounts', '--use-conda', '-F', '--wrapper-prefix', 'file:///var/folders/2h/x3d2xrpd66908__bf_8j7sqc0000gn/T/tmpf7zavp8t/', '--conda-cleanup-pkgs', '--printshellcmds', '--show-failed-logs']' returned non-zero exit status 1.

../../../../opt/miniconda3/envs/test-snakemake-wrappers/lib/python3.11/subprocess.py:413: CalledProcessError
------------------------------------------------------------------- Captured stderr call --------------------------------------------------------------------
Building DAG of jobs...
Creating conda environment /var/folders/2h/x3d2xrpd66908__bf_8j7sqc0000gn/T/tmpf7zavp8t/master/bio/subread/featurecounts/environment.yaml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /var/folders/2h/x3d2xrpd66908__bf_8j7sqc0000gn/T/tmpf7zavp8t/master/bio/subread/featurecounts/environment.yaml:
Command:
mamba env create --quiet --file "/private/var/folders/2h/x3d2xrpd66908__bf_8j7sqc0000gn/T/tmpf7zavp8t/test/.snakemake/conda/3702bb70d3b60f995a8bde3b943486da_.yaml" --prefix "/private/var/folders/2h/x3d2xrpd66908__bf_8j7sqc0000gn/T/tmpf7zavp8t/test/.snakemake/conda/3702bb70d3b60f995a8bde3b943486da_"
Output:
Traceback (most recent call last):
  File "/Users/oliverkuchler/opt/miniconda3/condabin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/Users/oliverkuchler/opt/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 53, in <module>
    import mamba.mamba_api as api
ImportError: dlopen(/Users/oliverkuchler/opt/miniconda3/lib/python3.9/site-packages/mamba/mamba_api.cpython-39-darwin.so, 2): Library not loaded: @rpath/libarchive.13.dylib
  Referenced from: /Users/oliverkuchler/opt/miniconda3/lib/python3.9/site-packages/mamba/mamba_api.cpython-39-darwin.so
  Reason: image not found

usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
================================================================== short test summary info ==================================================================
FAILED test.py::test_subread_featurecounts - subprocess.CalledProcessError: Command '['snakemake', '--cores', '1', 'results/a.featureCounts', 'results/a.featureCounts.summary', 'results/a.featureCo...
============================================================= 1 failed, 428 deselected in 6.51s =============================================================

```

However, I just realized that I cannot make any of these test run on my machine and they all return the same error. Not sure, whether the reason for that might not be on my side...

**Comment by KuechlerO** [comment]
Solution found [here](https://github.com/mamba-org/mamba/issues/1826): 
Something seemed to be wrong with my `libarchive` package installation in the conda-environment.

**Fix:**
`conda install libarchive -n base -c conda-forge`
